[package]
name = "holostats-server"
version = "0.1.0"
authors = ["PoiScript <poiscript@gmail.com>"]
edition = "2018"
# build = "build.rs"

[dependencies]
bytes = "0.5.6"
chrono = { version = "0.4.19", features = ["serde"] }
futures = "0.3.8"
reqwest = { version = "0.10.9", default-features = false, features = ["json", "rustls-tls"] }
roxmltree = "0.14.0"
serde = { version = "1.0.118", features = ["derive"] }
serde_json = "1.0.61"
sqlx = { version = "0.4.2", default-features = false, features = ["runtime-tokio", "macros", "postgres", "chrono"] }
tokio = { version = "0.2.22", features = ["macros"] }
url = "2.2.0"
warp = { version = "0.2.5", default-features = false }
cfg-if = "1.0.0"
serde_with = "1.6.0"
hmac = "0.10.1"
sha2 = "0.9.2"
hex = "0.4.2"

[profile.release]
lto = true

[[bin]]
name = "api"
path = "src/api/main.rs"

[[bin]]
name = "stream_stat"
path = "src/stream_stat/main.rs"

[[bin]]
name = "channel_stat"
path = "src/channel_stat/main.rs"

[[bin]]
name = "subscribe"
path = "src/subscribe/main.rs"

[dev-dependencies]
pretty_assertions = "0.6.1"
