[package]
name = "holostats-server"
version = "0.1.0"
authors = ["PoiScript <poiscript@gmail.com>"]
edition = "2018"
build = "build.rs"

[dependencies]
bytes = "0.5.4"
chrono = { version = "0.4.10", features = ["serde"] }
futures = "0.3.1"
reqwest = { version = "0.10", default-features = false, features = ["json", "rustls-tls" ] }
roxmltree = "0.9.0"
serde = { version = "1.0.104", features = ["derive"] }
serde_json = "1.0.45"
sqlx = { version = "0.2", default-features = false, features = [ "runtime-tokio", "macros", "postgres", "chrono" ] }
tokio = { version = "0.2", features = ["macros"] }
url = "2.1.1"
warp = "0.2"

[profile.release]
lto = true

[[bin]]
name = "server"
path = "src/main.rs"

[[bin]]
name = "stream_stat"
path = "src/stream_stat.rs"

[[bin]]
name = "channel_stat"
path = "src/channel_stat.rs"
