[package]
name = "holostats-server"
version = "0.1.0"
authors = ["PoiScript <poiscript@gmail.com>"]
edition = "2018"
# build = "build.rs"

[dependencies]
bytes = "0.5.4"
chrono = { version = "0.4.11", features = ["serde"] }
futures = "0.3.4"
reqwest = { version = "0.10.4", default-features = false, features = ["json", "rustls-tls"] }
roxmltree = "0.11.0"
serde = { version = "1.0.114", features = ["derive"] }
serde_json = "1.0.52"
sqlx = { version = "0.3.4", default-features = false, features = ["runtime-tokio", "macros", "postgres", "chrono"] }
tokio = { version = "0.2.20", features = ["macros"] }
url = "2.1.1"
warp = { version = "0.2.2", default-features = false }
cfg-if = "0.1.10"

[profile.release]
lto = true

[[bin]]
name = "server"
path = "src/main.rs"

[[bin]]
name = "stream_stat"
path = "src/stream_stat.rs"

[[bin]]
name = "channel_stat"
path = "src/channel_stat.rs"

[[bin]]
name = "subscribe"
path = "src/subscribe.rs"

[dev-dependencies]
pretty_assertions = "0.6.1"
