[package]
name = "holostats-config"
version = "0.1.0"
authors = ["PoiScript <poiscript@gmail.com>"]
edition = "2018"
publish = false

[lib]
path = "lib.rs"

[dependencies]
once_cell = "1.8.0"
serde = { version = "1.0.130", features = ["derive"] }
toml = "0.5.8"
