name: Angular

on:
  push:
    paths:
      - web
      - .github/workflows/angular.yml
  pull_request:
    paths:
      - web

defaults:
  run:
    working-directory: web

jobs:
  build_and_test:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Add yarn global bin to path
        run: echo "::add-path::$(yarn global bin)"

      - name: Cache
        uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Use Node 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x

      - name: Run Prettier
        run: |
          yarn global add prettier
          prettier --check --ignore-path .gitignore 'src/**/*.{ts,js,json.html,scss}'

      - name: Build
        run: |
          yarn install
          sed -i "s/GIT_COMMIT_HASH/$(git rev-parse --short HEAD)/" src/environments/*
          yarn ng run holostats:app-shell:production
          yarn ng run holostats:workers:production

      - name: Upload dist
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: |
            web/dist
            web/workers/dist
          if-no-files-found: error

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build_and_test
    if: github.ref == 'refs/heads/master'

    steps:
      - name: Download dist
        uses: actions/download-artifact@v2
        with:
          name: dist

      - name: Deploy
        uses: cloudflare/wrangler-action@1.3.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          environment: prod
          workingDirectory: web
