name: Web Dev

on:
  push:
    branches:
      - dev
    paths:
      - web/**
      - .github/workflows/web-dev.yml

defaults:
  run:
    working-directory: web

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Cache
        uses: actions/cache@v1
        with:
          path: web/node_modules
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Use Node 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x

      - name: Install dependencies
        run: yarn install --prefer-offline

      - name: Run Prettier
        run: yarn prettier --check --ignore-path .gitignore 'src/**/*.{ts,js,json.html,scss}'

      - name: Build
        run: |
          sed -i "s/GIT_COMMIT_HASH/$(git rev-parse --short HEAD)/" src/environments/*
          yarn build --prod --outputHashing=none --serviceWorker=false

      - name: Build workers
        run: yarn tsc -P workers/tsconfig.json

      - name: Deploy
        uses: cloudflare/wrangler-action@1.3.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          workingDirectory: web
          environment: dev
