name: Web Dev

on:
  push:
    branches:
      - dev
    paths:
      - web/**
      - .github/workflows/web-dev.yml

defaults:
  run:
    working-directory: web

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Cache
        uses: actions/cache@v1
        with:
          path: web/node_modules
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Use Node 12
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Install dependencies
        run: yarn install --prefer-offline

      - name: Run Prettier
        run: yarn prettier --check --ignore-path .gitignore 'src/**/*.{ts,js,json.html,scss}'

      - name: Build
        run: yarn build --prod --outputHashing=none --serviceWorker=false

      - name: Setup playwright
        uses: microsoft/playwright-github-action@v1

      - name: Run e2e
        continue-on-error: true
        run: |
          node e2e/server.js &
          yarn e2e
